### signup
POST http://localhost:8080/signup
Content-Type: application/json

{
  "username": "User3",
  "password": "password"
}

### signin
POST http://localhost:8080/signin
Content-Type: application/json

{
  "username": "User3",
  "password": "password"
}

### secret
< {%
    request.variables.set("bearer", "")
%}
GET http://localhost:8080/secret
Content-Type: application/json
Authorization: Bearer {{bearer}}