### signup
POST http://localhost:8080/signup
Content-Type: application/json

{
  "username": "User3",
  "password": "password"
}

### signin
POST http://localhost:8080/signin
Content-Type: application/json

{
  "username": "User3",
  "password": "password"
}

### secret
GET http://localhost:8080/secret
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJqd3QtYXVkaWVuY2UiLCJpc3MiOiJodHRwczovLzAuMC4wLjA6ODA4MCIsImV4cCI6MTY3NzQzOTAwOSwidXNlcklkIjoiNjlmMjRlYWQtMzI2YS00MDliLThlZjctMzUyMzJhMDIwZjA4IiwidXNlcm5hbWUiOiJVc2VyMyJ9.IHBG7nzIYklPg5V_iOXrJ_apxarTgTowEqaQahCuk0I